### ISSUE TITLE
Implement global try/catch error to catch all unexpected js errors

### ISSUE THREAD

**Issue by amcoho** [smohadjer/formwizard#7]
catch block should de-initialize all the js initialization work so user can use the no-js version.

**Comment by smohadjer** [comment]
I will insert an intentional error in step 2 so we can test this scenario. If error happens I will remove all event listeners. I don’t think we need to do anything else.

**Comment by smohadjer** [comment]
On a second thought, I don't think we need this. Using a global try/catch in Formwizrd class would only catch errors thrown by code in that class, which is not what we want since we can deal with such errors during testing and before run-time. Errors thrown by 3rd party code would happen either before or after class has initialised which in either case would not harm the Formwizard. If error happens before,  Formwizard won't initialise and form will run without js enhancements which is fine. If error happens after, it has no impact on Formwizard class.

**Comment by smohadjer** [comment]
@amcoho Should we close this?
